/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as RegisterUserRouteImport } from './routes/registerUser'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ManualProgramCreationRouteImport } from './routes/manualProgramCreation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AiProgramFactoryRouteImport } from './routes/aiProgramFactory'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterUserRoute = RegisterUserRouteImport.update({
  id: '/registerUser',
  path: '/registerUser',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualProgramCreationRoute = ManualProgramCreationRouteImport.update({
  id: '/manualProgramCreation',
  path: '/manualProgramCreation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AiProgramFactoryRoute = AiProgramFactoryRouteImport.update({
  id: '/aiProgramFactory',
  path: '/aiProgramFactory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aiProgramFactory': typeof AiProgramFactoryRoute
  '/login': typeof LoginRoute
  '/manualProgramCreation': typeof ManualProgramCreationRoute
  '/profile': typeof ProfileRoute
  '/registerUser': typeof RegisterUserRoute
  '/training': typeof TrainingRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aiProgramFactory': typeof AiProgramFactoryRoute
  '/login': typeof LoginRoute
  '/manualProgramCreation': typeof ManualProgramCreationRoute
  '/profile': typeof ProfileRoute
  '/registerUser': typeof RegisterUserRoute
  '/training': typeof TrainingRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aiProgramFactory': typeof AiProgramFactoryRoute
  '/login': typeof LoginRoute
  '/manualProgramCreation': typeof ManualProgramCreationRoute
  '/profile': typeof ProfileRoute
  '/registerUser': typeof RegisterUserRoute
  '/training': typeof TrainingRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aiProgramFactory'
    | '/login'
    | '/manualProgramCreation'
    | '/profile'
    | '/registerUser'
    | '/training'
    | '/workout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aiProgramFactory'
    | '/login'
    | '/manualProgramCreation'
    | '/profile'
    | '/registerUser'
    | '/training'
    | '/workout'
  id:
    | '__root__'
    | '/'
    | '/aiProgramFactory'
    | '/login'
    | '/manualProgramCreation'
    | '/profile'
    | '/registerUser'
    | '/training'
    | '/workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiProgramFactoryRoute: typeof AiProgramFactoryRoute
  LoginRoute: typeof LoginRoute
  ManualProgramCreationRoute: typeof ManualProgramCreationRoute
  ProfileRoute: typeof ProfileRoute
  RegisterUserRoute: typeof RegisterUserRoute
  TrainingRoute: typeof TrainingRoute
  WorkoutRoute: typeof WorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registerUser': {
      id: '/registerUser'
      path: '/registerUser'
      fullPath: '/registerUser'
      preLoaderRoute: typeof RegisterUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manualProgramCreation': {
      id: '/manualProgramCreation'
      path: '/manualProgramCreation'
      fullPath: '/manualProgramCreation'
      preLoaderRoute: typeof ManualProgramCreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aiProgramFactory': {
      id: '/aiProgramFactory'
      path: '/aiProgramFactory'
      fullPath: '/aiProgramFactory'
      preLoaderRoute: typeof AiProgramFactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiProgramFactoryRoute: AiProgramFactoryRoute,
  LoginRoute: LoginRoute,
  ManualProgramCreationRoute: ManualProgramCreationRoute,
  ProfileRoute: ProfileRoute,
  RegisterUserRoute: RegisterUserRoute,
  TrainingRoute: TrainingRoute,
  WorkoutRoute: WorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
